trigger:
  - iteration_24.2.4

pool:
  vmImage: "ubuntu-latest"
  
variables:
  tag: '$(Build.BuildId)'
steps:
   - task: Install Node
     inputs:
       versionSpec: "18.17.0"
     displayName: "Install Node.js"

   - script: |
      npm install -g vsts-npm-auth
      vsts-npm-auth -config .npmrc
     displayName: "Authenticate to Azure DevOps"

   - script: |
       npm install
     displayName: "npm install"

   - script: |
       npm run build
     displayName: "npm build"

   - script: |
       docker login $(dockerId).azurecr.io -u $(dockerId) -p $pswd
       docker build -f docker/dev/Dockerfile -t $(dockerId).azurecr.io/$(imageName):$(Build.BuildId) --build-arg ISSUER=$(ISSUER) --build-arg CLIENT=$(CLIENT) . 
       docker push $(dockerId).azurecr.io/$(imageName):$(Build.BuildId)
     env:
       pswd: $(dockerPassword)
     displayName: "Build and Push Docker Image for Digital Installed Base Application"