// The Redux action constants are stored in this file

const LOAD_SCHEMA = "LOAD_SCHEMA";
const LOAD_SCHEMA_SUCCESS = "LOAD_SCHEMA_SUCCESS";
const LOAD_SCHEMA_ERROR = "LOAD_SCHEMA_ERROR";
const UPDATE_PAGE_CONFIG = "UPDATE_PAGE_CONFIG";
const IS_LOADING = "IS_LOADING";

export { LOAD_SCHEMA, LOAD_SCHEMA_SUCCESS, LOAD_SCHEMA_ERROR, UPDATE_PAGE_CONFIG, IS_LOADING };
