export const TECHNOLOGY_TYPES_OPTIONS = {
  FLOW_ID: "FLOW",
  VISCOSITY_ID: "VISCOSITY"
};

Object.freeze(TECHNOLOGY_TYPES_OPTIONS);

export const FLUID_SOURCE_OPTIONS = {
  DATABASE: "DATABASE",
  CUSTOM: "CUSTOM"
};

Object.freeze(FLUID_SOURCE_OPTIONS);
