export const FIELD_TYPE = {
  TILE_THUMBNAIL: "TILE_THUMBNAIL",
  TABLE_INPUT: "TABLE_INPUT",
  SINGLE_SELECT: "SINGLE_SELECT",
  LABEL_TEXT: "LABEL_TEXT",
  CUSTOM_BUTTON_GROUP: "CUSTOM_BUTTON_GROUP",
  RADIO_INPUT: "RADIO_INPUT",
  TEXT_INPUT: "TEXT_INPUT"
};

Object.freeze(FIELD_TYPE);
